Repository keptn/community, pull requests merged in 2022-03, with the labels that each got.

#111 docs: add `Suraj Banakar` to potential mentors
  mentorship/gsoc/2022/project-ideas.md
Labels: gsoc

#107 Document the Keptn Advisory Board
  README.md
  advisory-board.md
Labels: contributing, governance

#128 Add transparent Keptn Icon
  branding/README.md
  branding/logos/keptn-icon-transparent.png
Labels: artwork

#135 Document mentorship and outreach programs, including LFX mentorship
  README.md
  mentorship/README.md
  mentorship/lfx-mentorship/README.md
Labels: community, documentation

#138 add project description for gitops integrations (gsoc)
  mentorship/gsoc/2022/project-ideas.md
Labels: gsoc
